spring:
  datasource:
    url: jdbc:mysql://47.114.172.148:3306/cl_demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

server:
  port: 8082

lmm:


management:
  endpoints:
    web:
      exposure:
        include: "*"